name: setup
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18.17.1
        cache: 'pnpm'

    - name: Installing dependencies
      run: pnpm install --frozen-lockfile
      shell: bash
